image: docker:stable

stages:
  - build
  - deploy

variables:
  APP_PORT: 8092
  DOCKER_DRIVER: overlay
  APP_NAME: ods-cli
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

##Build the project
package-build:
  image: alpine
  stage: build
  before_script:
    - apk add --update zip
  only:
    - yj/master-ci
  script: 
    - pwd
    - ls
    - zip -r ods-cli.zip .
    - ls
    - pwd
  artifacts:
    paths:
      - ods-cli.zip

aws-service-deploy:
  image: alpine
  stage: deploy
  only:
    - yj/master-ci
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$CI_CD_PEM" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - ssh -o StrictHostKeyChecking=no ubuntu@34.227.114.101 "echo 'Hello' "
    - scp -o StrictHostKeyChecking=no ods-cli.zip ubuntu@34.227.114.101:/home/ubuntu/
    - ssh -o StrictHostKeyChecking=no ubuntu@34.227.114.101 "ls /home/ubuntu"

