image: docker:stable

stages:
  - build
  - deploy

variables:
  APP_PORT: 8092
  DOCKER_DRIVER: overlay
  APP_NAME: ods-cli
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

##Build the project
package-build:
  image: maven:3-jdk-11
  stage: build
  only:
    - yj/master-ci
  script: 
    - pwd
    - ls
  artifacts:
    paths:
      - target/*.zip

aws-service-deploy:
  image: docker:19.03.12
  stage: deploy
  only:
    - yj/master-ci
  services:
    - docker:19.03.12-dind
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$CI_CD_PEM" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - ssh -o StrictHostKeyChecking=no ubuntu@34.227.114.101 "echo 'Hello' "

