name: ODS cli publish to pypi

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Bump version
      run: |
        pip install bump2version
        current_version=$(grep -oP '__version__ = "\K[^"]+' _version.py)'  # Extract current version
        bump2version --current-version "$current_version" patch

    - name: Build and publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        python setup.py sdist bdist_wheel
        pip install twine
        twine upload dist/*
