name: ODS cli publish to pypi

on:
  release:
    types:
      - "published"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.10 ]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install twine setuptools build wheel
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Update version
        run: |
          sed -i "s/<version>/${{ github.event.release.tag_name }}/g" setup.py

      - name: Build odscli
        run: |
          python setup.py sdist bdist_wheel

      - name: Build and publish
        shell: bash
        run: |
          twine upload -r pypi dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
